---

- name: manage webserver
  hosts: jenkins
  gather_facts: false
  become: true

  roles:
    - webserver

- name: manage users            
  hosts: localhost
  gather_facts: false
  become: true
    #  vars:
    #   user_name: alade
  tasks:
    - name: create and manage users
      user:
          name: "{{ user_name }}"
          state: present 

