---
# tasks file for webserver

    - name: manage package
      package:
          name: "{{ package_name }}"
          state: present
    - name: manage service
      service:
          name: "{{ service_name }}"
          state: started
    - name: deploy site
      copy:
          src: index.html
          dest: "{{ doc_root }}"
      notify:
        - restart_webservice
